exclude = [".direnv/**", "target/**"]
include = [
    "Cargo.toml",
    "clippy.toml",
    "deny.toml",
    "rust-toolchain.toml",
    "taplo.toml",
    "packages/**/*.toml",
    "config.example.toml",
]

[formatting]
align_entries  = true
indent_string  = "    "
reorder_arrays = false
reorder_keys   = true
